export const CAMPUS_LOCATIONS = [
  "Ground Floor - Admin Office",
  "Ground Floor - Seminar Hall",
  "Ground Floor - Sports Room",
  "Ground Floor - Principal's Office",
  "Ground Floor - Washroom",
  "First Floor - Classroom 101",
  "First Floor - Classroom 102",
  "First Floor - Classroom 103",
  "First Floor - Classroom 104",
  "First Floor - Classroom 111",
  "First Floor - Lab",
  "First Floor - NSS Room",
  "First Floor - Staff Room",
  "First Floor - Washroom",
  "Second Floor - Classroom 201",
  "Second Floor - Classroom 202",
  "Second Floor - Classroom 203",
  "Second Floor - Classroom 204",
  "Second Floor - Classroom 211",
  "Second Floor - Lab",
  "Second Floor - Library",
  "Second Floor - Staff Room",
  "Second Floor - Washroom",
  "Third Floor - Classroom 301",
  "Third Floor - Classroom 302",
  "Third Floor - Classroom 303",
  "Third Floor - Classroom 304",
  "Third Floor - Classroom 311",
  "Third Floor - Lab",
  "Third Floor - Staff Room",
  "Third Floor - Washroom",
  "Fourth Floor - CR1",
  "Fourth Floor - CR2",
  "Fourth Floor - CR3",
  "Fourth Floor - CR4",
  "Fourth Floor - CR5",
  "Fourth Floor - CR6",
  "Fourth Floor - Lab 1",
  "Fourth Floor - Lab 2",
  "Fourth Floor - Lab 3",
  "Fourth Floor - Lab 4",
  "Fourth Floor - Lab 5",
  "Fourth Floor - Lab 6",
  "Fourth Floor - Lab 7",
  "Fourth Floor - Lab 8",
  "Fourth Floor - Staff Room",
  "Fourth Floor - Washroom",
  "Canteen",
  "Auditorium Floor - GST Auditorium",
  "Auditorium Floor - Mechanical Workshop 1",
  "Auditorium Floor - Mechanical Workshop 2",
  "Common - Staircase",
  "Common - Corridor",
  "Common - Entrance Gate",
  "Common - Parking Area",
];
